name: Landlord
version: ${project.version}
main: net.saifs.landlord.Landlord
authors: [Saif]
commands:
  listhomes:
    aliases: [homes]
  cloudyhome:
    aliases: [home]
  playerhome:
    aliases: [playerhomes]
  sethome:
    description: Used to set your home
  deletehome:
    aliases: [delhome]
  modifyhomecount:
    aliases: [modhomes]
    usage: /<command>
permissions:
  landlord.user:
    default: true
  landlord.admin:
    default: op
